In [1]:
import pandas as pd
import numpy as np

## 1. Crea il DataFrame **vendite** che contiene la quantità di torte, biscotti e taralli (colonne) nei diversi giorni della settimana (righe).

  Inserisci valori casuali compresi tra 5 e 50 (np.random.seed(100)).

In [2]:
def create_df():
    np.random.seed(100)
    data = {
        'torte': np.random.randint(low=5, high=50, size=7),
        'biscotti': np.random.randint(low=5, high=50, size=7),
        'taralli': np.random.randint(low=5, high=50, size=7)
    }
    index = ['lun', 'mar', 'mer', 'gio', 'ven', 'sab', 'dom']
    return pd.DataFrame(data, index)


df = create_df()
df

# Alternativa
#np.random.seed(100)
#vendite = pd.DataFrame(np.random.randint(5,50, size=(7,3)), columns=['torte', 'biscotti', 'taralli'], index=['LUN', 'MAR', 'MER', 'GIO', 'VEN', 'SAB', 'DOM'])

     torte  biscotti  taralli
lun     13        35       20
mar     29        39       41
mer      8         7       48
gio     44        39       21
ven     28        19       14
sab     20        39       34
dom     15        29       27

In [3]:
type(df.torte)

pandas.core.series.Series

In [4]:
type(df.loc['lun'])

pandas.core.series.Series

## 2. Visualizza le vendite di torte durante tutta la settimana.

In [5]:
df.torte
# Alternativa
# df['torte']

lun    13
mar    29
mer     8
gio    44
ven    28
sab    20
dom    15
Name: torte, dtype: int64

## 3. Ottieni le vendite del giovedi.

In [6]:
df.loc['gio']
# Alternativa
# df.iloc[3]

torte       44
biscotti    39
taralli     21
Name: gio, dtype: int64

## 4. Visualizza le vendite di biscotti e taralli dal mercoledì alla domenica.

In [7]:
df

     torte  biscotti  taralli
lun     13        35       20
mar     29        39       41
mer      8         7       48
gio     44        39       21
ven     28        19       14
sab     20        39       34
dom     15        29       27

In [8]:
df.loc['mer':'dom', ['biscotti', 'taralli']]
# Alternative
# df.loc['mer':'dom', 'biscotti':'taralli']
# df.iloc[2:7, [1, 2]]
# df.iloc[2:, [1, 2]]
# df.iloc[2:,1:3]
# nota come con le label l'endpoint sia incluso, mentre con gli int l'endpoint sia escluso

     biscotti  taralli
mer         7       48
gio        39       21
ven        19       14
sab        39       34
dom        29       27

## 5. Qual è il totale delle vendite per ogni prodotto durante la settimana?

In [9]:
df.sum() # default axis=0

torte       157
biscotti    207
taralli     205
dtype: int64

## 6. Qual è il giorno con il massimo delle vendite di torte?

In [10]:
df.torte.idxmax()

'gio'

In [11]:
df.torte.argmax()

np.int64(3)

## 7. Aggiungi la colonna **Totale Vendite Giorno** che rappresenta la somma delle vendite di tutti i prodotti per ciascun giorno.

In [12]:
df['tot'] = df.sum(axis=1)
df

     torte  biscotti  taralli  tot
lun     13        35       20   68
mar     29        39       41  109
mer      8         7       48   63
gio     44        39       21  104
ven     28        19       14   61
sab     20        39       34   93
dom     15        29       27   71

## 8. Quanti e quali giorni hanno avuto un totale di vendite giornaliere superiori a 80?

Quanti

In [13]:
df.tot > 80

lun    False
mar     True
mer    False
gio     True
ven    False
sab     True
dom    False
Name: tot, dtype: bool

In [14]:
(df.tot > 80).sum()

np.int64(3)

Quali

In [15]:
df[df.tot > 80]

     torte  biscotti  taralli  tot
mar     29        39       41  109
gio     44        39       21  104
sab     20        39       34   93

In [16]:
df[df.tot > 80].index

Index(['mar', 'gio', 'sab'], dtype='object')

In [17]:
df[df.tot > 80].index.values

array(['mar', 'gio', 'sab'], dtype=object)