In [1]:
import pandas as pd
import numpy as np

# Analisi dei dati anagrafici dei dipendenti di un'azienda

## 1. Inserisci in un dataframe il contenuto del file "dipendenti.csv".

   Quante righe e quante colonne ci sono? Ci sono duplicati?

In [2]:
df = pd.read_csv('../data/dipendenti.csv', sep=';')
df

,Nome,Cognome,Età,Anni di esperienza,Dipartimento,Stipendio,Città
0,Marco,Rossi,NaN,2,Vendite,30000,Milano
1,Anna,Bianchi,32.0,7,Information Technology,45000,Roma
2,Luca,Verdi,28.0,5,Vendite,37000,Milano
3,Sara,Neri,40.0,12,Information Technology,62000,Roma
4,Giorgio,Rossi,45.0,20,Human Resources,70000,Torino
5,Francesca,Ferrari,NaN,15,Human Resources,58000,Roma
6,Elena,Romano,34.0,8,Information Technology,52000,Milano
7,Simone,Gialli,30.0,4,Vendite,33000,Napoli
8,Valentina,Rossi,30.0,9,Vendite,32000,Napoli
9,Giorgio,Rossi,45.0,20,Human Resources,70000,Torino
10,Anna,Bianchi,32.0,7,Vendite,45000,Milano
11,Sara,Bianchi,32.0,7,Vendite,25000,Roma
12,Sara,Romano,33.0,8,Information Technology,40000,Milano
13,Simone,Gialli,30.0,4,Vendite,33000,Napoli
14,Valentina,Rossi,30.0,12,Vendite,42000,Milano

In [3]:
df.shape

(15, 7)

In [4]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10    False
11    False
12    False
13     True
14    False
dtype: bool

In [5]:
df.duplicated().sum()

np.int64(2)

## 2. Crea una nuova colonna chiamata **Livello Esperienza**, utilizzando la colonna **Anni di esperienza**. Se l'esperienza è minore di 5 anni, mappa il valore a "Junior", tra 5 e 10 a "Mid" e più di 10 a "Senior".

In [6]:
def mapping(x):
    if x < 5:
        return "Junior"
    elif x <= 10:
        return "Mid"
    else:
        return "Senior"

df['Livello Esperienza'] = df['Anni di esperienza'].map(mapping)
df

,Nome,Cognome,Età,Anni di esperienza,Dipartimento,Stipendio,Città,Livello Esperienza
0,Marco,Rossi,NaN,2,Vendite,30000,Milano,Junior
1,Anna,Bianchi,32.0,7,Information Technology,45000,Roma,Mid
2,Luca,Verdi,28.0,5,Vendite,37000,Milano,Mid
3,Sara,Neri,40.0,12,Information Technology,62000,Roma,Senior
4,Giorgio,Rossi,45.0,20,Human Resources,70000,Torino,Senior
5,Francesca,Ferrari,NaN,15,Human Resources,58000,Roma,Senior
6,Elena,Romano,34.0,8,Information Technology,52000,Milano,Mid
7,Simone,Gialli,30.0,4,Vendite,33000,Napoli,Junior
8,Valentina,Rossi,30.0,9,Vendite,32000,Napoli,Mid
9,Giorgio,Rossi,45.0,20,Human Resources,70000,Torino,Senior
10,Anna,Bianchi,32.0,7,Vendite,45000,Milano,Mid
11,Sara,Bianchi,32.0,7,Vendite,25000,Roma,Mid
12,Sara,Romano,33.0,8,Information Technology,40000,Milano,Mid
13,Simone,Gialli,30.0,4,Vendite,33000,Napoli,Junior
14,Valentina,Rossi,30.0,12,Vendite,42000,Milano,Senior

In [7]:
# Alternativa
df['Livello Esperienza_cut'] = pd.cut(df['Anni di esperienza'].values, [0,5,11,100], right=False, labels = ['Junior', 'Mid', 'Senior'])

## 3. Sostituisci i nomi dei dipartimenti con le seguenti abbreviazioni: Vendite -> 'VEN', Information Technology -> 'IT', Human Resources -> 'HR'. Quanti dipendenti ci sono per ogni dipartimento?

In [8]:
df

,Nome,Cognome,Età,Anni di esperienza,Dipartimento,Stipendio,Città,Livello Esperienza,Livello Esperienza_cut
0,Marco,Rossi,NaN,2,Vendite,30000,Milano,Junior,Junior
1,Anna,Bianchi,32.0,7,Information Technology,45000,Roma,Mid,Mid
2,Luca,Verdi,28.0,5,Vendite,37000,Milano,Mid,Mid
3,Sara,Neri,40.0,12,Information Technology,62000,Roma,Senior,Senior
4,Giorgio,Rossi,45.0,20,Human Resources,70000,Torino,Senior,Senior
5,Francesca,Ferrari,NaN,15,Human Resources,58000,Roma,Senior,Senior
6,Elena,Romano,34.0,8,Information Technology,52000,Milano,Mid,Mid
7,Simone,Gialli,30.0,4,Vendite,33000,Napoli,Junior,Junior
8,Valentina,Rossi,30.0,9,Vendite,32000,Napoli,Mid,Mid
9,Giorgio,Rossi,45.0,20,Human Resources,70000,Torino,Senior,Senior
10,Anna,Bianchi,32.0,7,Vendite,45000,Milano,Mid,Mid
11,Sara,Bianchi,32.0,7,Vendite,25000,Roma,Mid,Mid
12,Sara,Romano,33.0,8,Information Technology,40000,Milano,Mid,Mid
13,Simone,Gialli,30.0,4,Vendite,33000,Napoli,Junior,Junior
14,Valentina,Rossi,30.0,12,Vendite,42000,Milano,Senior,Senior

In [9]:
mapping = {'Vendite': 'VEN', 'Information Technology': 'IT', 'Human Resources': 'HR'}

In [10]:
df['Dipartimento'] = df['Dipartimento'].map(mapping)

In [11]:
df

,Nome,Cognome,Età,Anni di esperienza,Dipartimento,Stipendio,Città,Livello Esperienza,Livello Esperienza_cut
0,Marco,Rossi,NaN,2,VEN,30000,Milano,Junior,Junior
1,Anna,Bianchi,32.0,7,IT,45000,Roma,Mid,Mid
2,Luca,Verdi,28.0,5,VEN,37000,Milano,Mid,Mid
3,Sara,Neri,40.0,12,IT,62000,Roma,Senior,Senior
4,Giorgio,Rossi,45.0,20,HR,70000,Torino,Senior,Senior
5,Francesca,Ferrari,NaN,15,HR,58000,Roma,Senior,Senior
6,Elena,Romano,34.0,8,IT,52000,Milano,Mid,Mid
7,Simone,Gialli,30.0,4,VEN,33000,Napoli,Junior,Junior
8,Valentina,Rossi,30.0,9,VEN,32000,Napoli,Mid,Mid
9,Giorgio,Rossi,45.0,20,HR,70000,Torino,Senior,Senior
10,Anna,Bianchi,32.0,7,VEN,45000,Milano,Mid,Mid
11,Sara,Bianchi,32.0,7,VEN,25000,Roma,Mid,Mid
12,Sara,Romano,33.0,8,IT,40000,Milano,Mid,Mid
13,Simone,Gialli,30.0,4,VEN,33000,Napoli,Junior,Junior
14,Valentina,Rossi,30.0,12,VEN,42000,Milano,Senior,Senior

In [12]:
df.groupby('Dipartimento').size()

Dipartimento
HR     3
IT     4
VEN    8
dtype: int64

In [13]:
# Alternativa
df['Dipartimento'].value_counts()

Dipartimento
VEN    8
IT     4
HR     3
Name: count, dtype: int64

## 4. Crea un'altra colonna con i valori di età discretizzati in 5 gruppi, a quale gruppo di età appartiene la maggior parte dei dipendenti?

In [14]:
emin = df.Età.min()
emax = df.Età.max()
bins = np.linspace(emin - 1, emax, 5)
emin, emax, bins

(28.0, 45.0, array([27. , 31.5, 36. , 40.5, 45. ]))

In [15]:
new_col = pd.cut(df.Età, bins)
new_col

0              NaN
1     (31.5, 36.0]
2     (27.0, 31.5]
3     (36.0, 40.5]
4     (40.5, 45.0]
5              NaN
6     (31.5, 36.0]
7     (27.0, 31.5]
8     (27.0, 31.5]
9     (40.5, 45.0]
10    (31.5, 36.0]
11    (31.5, 36.0]
12    (31.5, 36.0]
13    (27.0, 31.5]
14    (27.0, 31.5]
Name: Età, dtype: category
Categories (4, interval[float64, right]): [(27.0, 31.5] < (31.5, 36.0] < (36.0, 40.5] < (40.5, 45.0]]

In [16]:
df['Età Discretizzata'] = new_col
df

,Nome,Cognome,Età,Anni di esperienza,Dipartimento,Stipendio,Città,Livello Esperienza,Livello Esperienza_cut,Età Discretizzata
0,Marco,Rossi,NaN,2,VEN,30000,Milano,Junior,Junior,NaN
1,Anna,Bianchi,32.0,7,IT,45000,Roma,Mid,Mid,"(31.5, 36.0]"
2,Luca,Verdi,28.0,5,VEN,37000,Milano,Mid,Mid,"(27.0, 31.5]"
3,Sara,Neri,40.0,12,IT,62000,Roma,Senior,Senior,"(36.0, 40.5]"
4,Giorgio,Rossi,45.0,20,HR,70000,Torino,Senior,Senior,"(40.5, 45.0]"
5,Francesca,Ferrari,NaN,15,HR,58000,Roma,Senior,Senior,NaN
6,Elena,Romano,34.0,8,IT,52000,Milano,Mid,Mid,"(31.5, 36.0]"
7,Simone,Gialli,30.0,4,VEN,33000,Napoli,Junior,Junior,"(27.0, 31.5]"
8,Valentina,Rossi,30.0,9,VEN,32000,Napoli,Mid,Mid,"(27.0, 31.5]"
9,Giorgio,Rossi,45.0,20,HR,70000,Torino,Senior,Senior,"(40.5, 45.0]"
10,Anna,Bianchi,32.0,7,VEN,45000,Milano,Mid,Mid,"(31.5, 36.0]"
11,Sara,Bianchi,32.0,7,VEN,25000,Roma,Mid,Mid,"(31.5, 36.0]"
12,Sara,Romano,33.0,8,IT,40000,Milano,Mid,Mid,"(31.5, 36.0]"
13,Simone,Gialli,30.0,4,VEN,33000,Napoli,Junior,Junior,"(27.0, 31.5]"
14,Valentina,Rossi,30.0,12,VEN,42000,Milano,Senior,Senior,"(27.0, 31.5]"

In [17]:
df['Età Discretizzata'].value_counts().idxmax()
# Alternative
#df.groupby('Età Discretizzata', observed=False).size().idxmax()
#df.groupby('Età Discretizzata', observed=False).agg('size').idxmax()

Interval(27.0, 31.5, closed='right')

Alternativa alla mia soluzione

In [18]:
df['Età Discretizzata'] = pd.cut(df['Età'].values, 5)#.codes

In [19]:
df['Età Discretizzata'].value_counts().idxmax()

Interval(27.983, 31.4, closed='right')

## 5. Sostituisci i valori mancanti della colonna età con il valore medio di età per i dipendenti dello stesso settore.

In [20]:
df.groupby(df['Dipartimento']).describe()

               Età                                                      \
             count       mean       std   min    25%   50%   75%   max
Dipartimento
HR             2.0  45.000000  0.000000  45.0  45.00  45.0  45.0  45.0
IT             4.0  34.750000  3.593976  32.0  32.75  33.5  35.5  40.0
VEN            7.0  30.285714  1.380131  28.0  30.00  30.0  31.0  32.0

             Anni di esperienza             ...             Stipendio  \
                          count       mean  ...   75%   max     count
Dipartimento                                ...
HR                          3.0  18.333333  ...  20.0  20.0       3.0
IT                          4.0   8.750000  ...   9.0  12.0       4.0
VEN                         8.0   6.250000  ...   7.5  12.0       8.0

                                                                        \
                 mean          std      min      25%      50%      75%
Dipartimento
HR            66000.0  6928.203230  58000.0  64000.0  70000.0  70000.0
IT            49750.0  9535.023160  40000.0  43750.0  48500.0  54500.0
VEN           34625.0  6479.362843  25000.0  31500.0  33000.0  38250.0


                  max
Dipartimento
HR            70000.0
IT            62000.0
VEN           45000.0

[3 rows x 24 columns]

In [21]:
mean_age_by_department = df.groupby('Dipartimento')['Età'].mean()
mean_age_by_department
# Alternativa
# df['Età'].groupby(df['Dipartimento']).mean()

Dipartimento
HR     45.000000
IT     34.750000
VEN    30.285714
Name: Età, dtype: float64

In [22]:
def fill_missing_age(row):
    if pd.isnull(row['Età']):
        return mean_age_by_department.get(row['Dipartimento'])
    else:
        return row['Età']
    
df['Età'] = df.apply(fill_missing_age, axis=1)
df

,Nome,Cognome,Età,Anni di esperienza,Dipartimento,Stipendio,Città,Livello Esperienza,Livello Esperienza_cut,Età Discretizzata
0,Marco,Rossi,30.285714,2,VEN,30000,Milano,Junior,Junior,NaN
1,Anna,Bianchi,32.000000,7,IT,45000,Roma,Mid,Mid,"(31.4, 34.8]"
2,Luca,Verdi,28.000000,5,VEN,37000,Milano,Mid,Mid,"(27.983, 31.4]"
3,Sara,Neri,40.000000,12,IT,62000,Roma,Senior,Senior,"(38.2, 41.6]"
4,Giorgio,Rossi,45.000000,20,HR,70000,Torino,Senior,Senior,"(41.6, 45.0]"
5,Francesca,Ferrari,45.000000,15,HR,58000,Roma,Senior,Senior,NaN
6,Elena,Romano,34.000000,8,IT,52000,Milano,Mid,Mid,"(31.4, 34.8]"
7,Simone,Gialli,30.000000,4,VEN,33000,Napoli,Junior,Junior,"(27.983, 31.4]"
8,Valentina,Rossi,30.000000,9,VEN,32000,Napoli,Mid,Mid,"(27.983, 31.4]"
9,Giorgio,Rossi,45.000000,20,HR,70000,Torino,Senior,Senior,"(41.6, 45.0]"
10,Anna,Bianchi,32.000000,7,VEN,45000,Milano,Mid,Mid,"(31.4, 34.8]"
11,Sara,Bianchi,32.000000,7,VEN,25000,Roma,Mid,Mid,"(31.4, 34.8]"
12,Sara,Romano,33.000000,8,IT,40000,Milano,Mid,Mid,"(31.4, 34.8]"
13,Simone,Gialli,30.000000,4,VEN,33000,Napoli,Junior,Junior,"(27.983, 31.4]"
14,Valentina,Rossi,30.000000,12,VEN,42000,Milano,Senior,Senior,"(27.983, 31.4]"

## 6. Verifica se, in media, lo stipendio di chi vive a Milano è superiore rispetto a quello di chi vive a Roma.

In [23]:
mean_salaries = df['Stipendio'].groupby(df['Città']).mean()
mean_salaries

Città
Milano    41000.000000
Napoli    32666.666667
Roma      47500.000000
Torino    70000.000000
Name: Stipendio, dtype: float64

In [24]:
type(mean_salaries)

pandas.core.series.Series

In [25]:
mean_salaries['Milano'] > mean_salaries['Roma']

np.False_

Alternativa alla mia soluzione

In [26]:
mean_milano = df[df['Città']=='Milano']['Stipendio'].mean()

In [27]:
mean_roma = df[df['Città']=='Roma']['Stipendio'].mean()

In [28]:
mean_milano > mean_roma

np.False_

In [29]:
mean_milano, mean_roma

(np.float64(41000.0), np.float64(47500.0))