**Analisi dei dati anagrafici dei dipendenti di un'azienda**

1. Inserisci in un dataframe il contenuto del file "dipendenti.csv".

   Quante righe e quante colonne ci sono? Ci sono duplicati?

In [1]:
import numpy as np
import pandas as pd

In [5]:
dipendenti = pd.read_csv('../data/dipendenti.csv', sep=';')
dipendenti

,Nome,Cognome,Età,Anni di esperienza,Dipartimento,Stipendio,Città
0,Marco,Rossi,NaN,2,Vendite,30000,Milano
1,Anna,Bianchi,32.0,7,Information Technology,45000,Roma
2,Luca,Verdi,28.0,5,Vendite,37000,Milano
3,Sara,Neri,40.0,12,Information Technology,62000,Roma
4,Giorgio,Rossi,45.0,20,Human Resources,70000,Torino
5,Francesca,Ferrari,NaN,15,Human Resources,58000,Roma
6,Elena,Romano,34.0,8,Information Technology,52000,Milano
7,Simone,Gialli,30.0,4,Vendite,33000,Napoli
8,Valentina,Rossi,30.0,9,Vendite,32000,Napoli
9,Giorgio,Rossi,45.0,20,Human Resources,70000,Torino
10,Anna,Bianchi,32.0,7,Vendite,45000,Milano
11,Sara,Bianchi,32.0,7,Vendite,25000,Roma
12,Sara,Romano,33.0,8,Information Technology,40000,Milano
13,Simone,Gialli,30.0,4,Vendite,33000,Napoli
14,Valentina,Rossi,30.0,12,Vendite,42000,Milano

In [14]:
dipendenti.shape[0] # num rows

15

In [14]:
dipendenti.shape[1] # num columns

15

In [10]:
len(dipendenti.columns)

7

In [ ]:
len(dipendenti.columns)

In [20]:
dipendenti.duplicated().sum()

np.int64(2)

2. Crea una nuova colonna chiamata **Livello Esperienza**, utilizzando la colonna **Anni di esperienza**. Se l'esperienza è minore di 5 anni, mappa il valore a "Junior", tra 5 e 10 a "Mid" e più di 10 a "Senior".

In [17]:
dipendenti['Livello Esperienza'] = dipendenti['Anni di esperienza']
dipendenti

,Nome,Cognome,Età,Anni di esperienza,Dipartimento,Stipendio,Città,Livello Esperienza
0,Marco,Rossi,NaN,2,Vendite,30000,Milano,2
1,Anna,Bianchi,32.0,7,Information Technology,45000,Roma,7
2,Luca,Verdi,28.0,5,Vendite,37000,Milano,5
3,Sara,Neri,40.0,12,Information Technology,62000,Roma,12
4,Giorgio,Rossi,45.0,20,Human Resources,70000,Torino,20
5,Francesca,Ferrari,NaN,15,Human Resources,58000,Roma,15
6,Elena,Romano,34.0,8,Information Technology,52000,Milano,8
7,Simone,Gialli,30.0,4,Vendite,33000,Napoli,4
8,Valentina,Rossi,30.0,9,Vendite,32000,Napoli,9
9,Giorgio,Rossi,45.0,20,Human Resources,70000,Torino,20
10,Anna,Bianchi,32.0,7,Vendite,45000,Milano,7
11,Sara,Bianchi,32.0,7,Vendite,25000,Roma,7
12,Sara,Romano,33.0,8,Information Technology,40000,Milano,8
13,Simone,Gialli,30.0,4,Vendite,33000,Napoli,4
14,Valentina,Rossi,30.0,12,Vendite,42000,Milano,12

In [23]:
def find_level(anni):
    if anni < 5:
        return 'Junior'
    elif anni <= 10:
        return 'Mid'
    else:
        return 'Senior'

In [25]:
dipendenti['Livello Esperienza'] = dipendenti['Anni di esperienza'].map(find_level)
dipendenti

,Nome,Cognome,Età,Anni di esperienza,Dipartimento,Stipendio,Città,Livello Esperienza
0,Marco,Rossi,NaN,2,Vendite,30000,Milano,Junior
1,Anna,Bianchi,32.0,7,Information Technology,45000,Roma,Mid
2,Luca,Verdi,28.0,5,Vendite,37000,Milano,Mid
3,Sara,Neri,40.0,12,Information Technology,62000,Roma,Senior
4,Giorgio,Rossi,45.0,20,Human Resources,70000,Torino,Senior
5,Francesca,Ferrari,NaN,15,Human Resources,58000,Roma,Senior
6,Elena,Romano,34.0,8,Information Technology,52000,Milano,Mid
7,Simone,Gialli,30.0,4,Vendite,33000,Napoli,Junior
8,Valentina,Rossi,30.0,9,Vendite,32000,Napoli,Mid
9,Giorgio,Rossi,45.0,20,Human Resources,70000,Torino,Senior
10,Anna,Bianchi,32.0,7,Vendite,45000,Milano,Mid
11,Sara,Bianchi,32.0,7,Vendite,25000,Roma,Mid
12,Sara,Romano,33.0,8,Information Technology,40000,Milano,Mid
13,Simone,Gialli,30.0,4,Vendite,33000,Napoli,Junior
14,Valentina,Rossi,30.0,12,Vendite,42000,Milano,Senior

In [27]:
dipendenti['Livello Esperienza cut'] = pd.cut(dipendenti['Anni di esperienza'].values, [0, 5, 11, 100], right=False, labels=['Junior', 'Mid', 'Senior'])
dipendenti

,Nome,Cognome,Età,Anni di esperienza,Dipartimento,Stipendio,Città,Livello Esperienza,Livello Esperienza cut
0,Marco,Rossi,NaN,2,Vendite,30000,Milano,Junior,Junior
1,Anna,Bianchi,32.0,7,Information Technology,45000,Roma,Mid,Mid
2,Luca,Verdi,28.0,5,Vendite,37000,Milano,Mid,Mid
3,Sara,Neri,40.0,12,Information Technology,62000,Roma,Senior,Senior
4,Giorgio,Rossi,45.0,20,Human Resources,70000,Torino,Senior,Senior
5,Francesca,Ferrari,NaN,15,Human Resources,58000,Roma,Senior,Senior
6,Elena,Romano,34.0,8,Information Technology,52000,Milano,Mid,Mid
7,Simone,Gialli,30.0,4,Vendite,33000,Napoli,Junior,Junior
8,Valentina,Rossi,30.0,9,Vendite,32000,Napoli,Mid,Mid
9,Giorgio,Rossi,45.0,20,Human Resources,70000,Torino,Senior,Senior
10,Anna,Bianchi,32.0,7,Vendite,45000,Milano,Mid,Mid
11,Sara,Bianchi,32.0,7,Vendite,25000,Roma,Mid,Mid
12,Sara,Romano,33.0,8,Information Technology,40000,Milano,Mid,Mid
13,Simone,Gialli,30.0,4,Vendite,33000,Napoli,Junior,Junior
14,Valentina,Rossi,30.0,12,Vendite,42000,Milano,Senior,Senior

3. Sostituisci i nomi dei dipartimenti con le seguenti abbreviazioni: Vendite -> 'VEN', Information Technology -> 'IT', Human Resources -> 'HR'. Quanti dipendenti ci sono per ogni dipartimento?

In [28]:
abbr = {'Vendite': 'VEN', 'Information Technology': 'IT', 'Human Resources': 'HR'}
dipendenti['Dipartimento'] = dipendenti['Dipartimento'].map(abbr)
dipendenti

,Nome,Cognome,Età,Anni di esperienza,Dipartimento,Stipendio,Città,Livello Esperienza,Livello Esperienza cut
0,Marco,Rossi,NaN,2,VEN,30000,Milano,Junior,Junior
1,Anna,Bianchi,32.0,7,IT,45000,Roma,Mid,Mid
2,Luca,Verdi,28.0,5,VEN,37000,Milano,Mid,Mid
3,Sara,Neri,40.0,12,IT,62000,Roma,Senior,Senior
4,Giorgio,Rossi,45.0,20,HR,70000,Torino,Senior,Senior
5,Francesca,Ferrari,NaN,15,HR,58000,Roma,Senior,Senior
6,Elena,Romano,34.0,8,IT,52000,Milano,Mid,Mid
7,Simone,Gialli,30.0,4,VEN,33000,Napoli,Junior,Junior
8,Valentina,Rossi,30.0,9,VEN,32000,Napoli,Mid,Mid
9,Giorgio,Rossi,45.0,20,HR,70000,Torino,Senior,Senior
10,Anna,Bianchi,32.0,7,VEN,45000,Milano,Mid,Mid
11,Sara,Bianchi,32.0,7,VEN,25000,Roma,Mid,Mid
12,Sara,Romano,33.0,8,IT,40000,Milano,Mid,Mid
13,Simone,Gialli,30.0,4,VEN,33000,Napoli,Junior,Junior
14,Valentina,Rossi,30.0,12,VEN,42000,Milano,Senior,Senior

4. Crea un'altra colonna con i valori di età discretizzati in 5 gruppi, a quale gruppo di età appartiene la maggior parte dei dipendenti?

In [34]:
dipendenti['Età Discr'] = pd.cut(dipendenti['Età'].values, 5)
dipendenti

,Nome,Cognome,Età,Anni di esperienza,Dipartimento,Stipendio,Città,Livello Esperienza,Livello Esperienza cut,Età Discr
0,Marco,Rossi,NaN,2,VEN,30000,Milano,Junior,Junior,NaN
1,Anna,Bianchi,32.0,7,IT,45000,Roma,Mid,Mid,"(31.4, 34.8]"
2,Luca,Verdi,28.0,5,VEN,37000,Milano,Mid,Mid,"(27.983, 31.4]"
3,Sara,Neri,40.0,12,IT,62000,Roma,Senior,Senior,"(38.2, 41.6]"
4,Giorgio,Rossi,45.0,20,HR,70000,Torino,Senior,Senior,"(41.6, 45.0]"
5,Francesca,Ferrari,NaN,15,HR,58000,Roma,Senior,Senior,NaN
6,Elena,Romano,34.0,8,IT,52000,Milano,Mid,Mid,"(31.4, 34.8]"
7,Simone,Gialli,30.0,4,VEN,33000,Napoli,Junior,Junior,"(27.983, 31.4]"
8,Valentina,Rossi,30.0,9,VEN,32000,Napoli,Mid,Mid,"(27.983, 31.4]"
9,Giorgio,Rossi,45.0,20,HR,70000,Torino,Senior,Senior,"(41.6, 45.0]"
10,Anna,Bianchi,32.0,7,VEN,45000,Milano,Mid,Mid,"(31.4, 34.8]"
11,Sara,Bianchi,32.0,7,VEN,25000,Roma,Mid,Mid,"(31.4, 34.8]"
12,Sara,Romano,33.0,8,IT,40000,Milano,Mid,Mid,"(31.4, 34.8]"
13,Simone,Gialli,30.0,4,VEN,33000,Napoli,Junior,Junior,"(27.983, 31.4]"
14,Valentina,Rossi,30.0,12,VEN,42000,Milano,Senior,Senior,"(27.983, 31.4]"

In [32]:
dipendenti['Età Discr'] = pd.cut(dipendenti['Età'].values, 5).codes
dipendenti

,Nome,Cognome,Età,Anni di esperienza,Dipartimento,Stipendio,Città,Livello Esperienza,Livello Esperienza cut,Età Discr
0,Marco,Rossi,NaN,2,VEN,30000,Milano,Junior,Junior,-1
1,Anna,Bianchi,32.0,7,IT,45000,Roma,Mid,Mid,1
2,Luca,Verdi,28.0,5,VEN,37000,Milano,Mid,Mid,0
3,Sara,Neri,40.0,12,IT,62000,Roma,Senior,Senior,3
4,Giorgio,Rossi,45.0,20,HR,70000,Torino,Senior,Senior,4
5,Francesca,Ferrari,NaN,15,HR,58000,Roma,Senior,Senior,-1
6,Elena,Romano,34.0,8,IT,52000,Milano,Mid,Mid,1
7,Simone,Gialli,30.0,4,VEN,33000,Napoli,Junior,Junior,0
8,Valentina,Rossi,30.0,9,VEN,32000,Napoli,Mid,Mid,0
9,Giorgio,Rossi,45.0,20,HR,70000,Torino,Senior,Senior,4
10,Anna,Bianchi,32.0,7,VEN,45000,Milano,Mid,Mid,1
11,Sara,Bianchi,32.0,7,VEN,25000,Roma,Mid,Mid,1
12,Sara,Romano,33.0,8,IT,40000,Milano,Mid,Mid,1
13,Simone,Gialli,30.0,4,VEN,33000,Napoli,Junior,Junior,0
14,Valentina,Rossi,30.0,12,VEN,42000,Milano,Senior,Senior,0

In [35]:
dipendenti['Età Discr'].max()

Interval(41.6, 45.0, closed='right')

5. Sostituisci i valori mancanti della colonna età con il valore medio di età per i dipendenti dello stesso settore.

In [57]:
medie = {}
#medie.append(dipendenti['Età'][])
medie['VEN'] = dipendenti['Età'].where(dipendenti['Dipartimento'] == 'VEN').mean()
medie['IT'] = dipendenti['Età'].where(dipendenti['Dipartimento'] == 'IT').mean()
medie['HR'] = dipendenti['Età'].where(dipendenti['Dipartimento'] == 'HR').mean()
medie

{'VEN': np.float64(30.285714285714285),
 'IT': np.float64(34.75),
 'HR': np.float64(45.0)}

In [58]:
dipendenti['Età'].fillna(medie['VEN'], inplace=True)
dipendenti['Età'].fillna(medie['IT'], inplace=True)
dipendenti['Età'].fillna(medie['HR'], inplace=True)
dipendenti

,Nome,Cognome,Età,Anni di esperienza,Dipartimento,Stipendio,Città,Livello Esperienza,Livello Esperienza cut,Età Discr
0,Marco,Rossi,30.285714,2,VEN,30000,Milano,Junior,Junior,NaN
1,Anna,Bianchi,32.000000,7,IT,45000,Roma,Mid,Mid,"(31.4, 34.8]"
2,Luca,Verdi,28.000000,5,VEN,37000,Milano,Mid,Mid,"(27.983, 31.4]"
3,Sara,Neri,40.000000,12,IT,62000,Roma,Senior,Senior,"(38.2, 41.6]"
4,Giorgio,Rossi,45.000000,20,HR,70000,Torino,Senior,Senior,"(41.6, 45.0]"
5,Francesca,Ferrari,30.285714,15,HR,58000,Roma,Senior,Senior,NaN
6,Elena,Romano,34.000000,8,IT,52000,Milano,Mid,Mid,"(31.4, 34.8]"
7,Simone,Gialli,30.000000,4,VEN,33000,Napoli,Junior,Junior,"(27.983, 31.4]"
8,Valentina,Rossi,30.000000,9,VEN,32000,Napoli,Mid,Mid,"(27.983, 31.4]"
9,Giorgio,Rossi,45.000000,20,HR,70000,Torino,Senior,Senior,"(41.6, 45.0]"
10,Anna,Bianchi,32.000000,7,VEN,45000,Milano,Mid,Mid,"(31.4, 34.8]"
11,Sara,Bianchi,32.000000,7,VEN,25000,Roma,Mid,Mid,"(31.4, 34.8]"
12,Sara,Romano,33.000000,8,IT,40000,Milano,Mid,Mid,"(31.4, 34.8]"
13,Simone,Gialli,30.000000,4,VEN,33000,Napoli,Junior,Junior,"(27.983, 31.4]"
14,Valentina,Rossi,30.000000,12,VEN,42000,Milano,Senior,Senior,"(27.983, 31.4]"

6. Verifica se, in media, lo stipendio di chi vive a Milano è superiore rispetto a quello di chi vive a Roma.

In [60]:
stipendi_medi = {}
stipendi_medi['M'] = dipendenti['Stipendio'].where(dipendenti['Città'] == 'Milano').mean()
stipendi_medi['R'] = dipendenti['Stipendio'].where(dipendenti['Città'] == 'Roma').mean()
stipendi_medi

{'M': np.float64(41000.0), 'R': np.float64(47500.0)}