In [138]:
import numpy as np
import pandas as pd

- In Data Analysis, a significant amount of time is spent on data preparation: loading, cleaning, transforming, and rearranging.
    - Such tasks are often reported to take up 80% or more of an analyst’s time.
- Pandas provides you with a high-level, flexible, and fast set of tools to enable you to manipulate data into the right form.
- Much of the design and implementation of pandas has been driven by the needs of real-world applications.

## Handling Missing Data
- Missing data occurs commonly in many data analysis applications.
    - All of the descriptive statistics on pandas objects exclude missing data by default.
- The missing data is represented in pandas with the floating-point value NaN (Not a Number).
    - We call this a sentinel value that can be easily detected.

- In pandas, missing data is also referred  as  NA (i.e., "not available").
- In statistics applications, NA means
    - data that does not exist
    - data that exists but was not observed

- When cleaning up data for analysis, it is often important to do analysis on the missing data itself to identify data
collection problems or potential biases in the data caused by missing data.
- The built-in Python None value is also treated as NA

In [139]:
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado'])

In [140]:
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
dtype: object

In [141]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [142]:
string_data[0] = None

In [143]:
string_data

0         None
1    artichoke
2          NaN
3      avocado
dtype: object

In [144]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

Note that both None and NaN are considered null values.

### Filtering Out Missing Data

- dropna: Remove missing values.

In [145]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])

In [146]:
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [147]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [148]:
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [149]:
data.notnull()

0     True
1    False
2     True
3    False
4     True
dtype: bool

In [150]:
#dropna is equivalent to
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

- dropna in Dataframe

In [151]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
                     [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])

In [152]:
data

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [153]:
data.dropna()

     0    1    2
0  1.0  6.5  3.0

In [154]:
cleaned = data.dropna(axis=1)

In [155]:
cleaned

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [156]:
data

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

- Passing how='all' will only drop rows that are all NA

In [157]:
data.dropna(how='all')

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [158]:
data.dropna(how='any')    # default

     0    1    2
0  1.0  6.5  3.0

- if you want to keep only rows containing a certain number of observations.

In [159]:
df = pd.DataFrame(np.random.randn(7, 3))
df.iloc[:4, 1] = np.nan
df.iloc[:2, 2] = np.nan

In [160]:
df

          0         1         2
0 -0.897483       NaN       NaN
1  0.681627       NaN       NaN
2  1.839922       NaN -0.580796
3  0.236613       NaN  0.377967
4 -0.950262  1.518228  0.299702
5 -1.091846 -1.637380 -0.366524
6  0.310111  0.333319 -0.358951

In [161]:
df.dropna(thresh=2)

          0         1         2
2  1.839922       NaN -0.580796
3  0.236613       NaN  0.377967
4 -0.950262  1.518228  0.299702
5 -1.091846 -1.637380 -0.366524
6  0.310111  0.333319 -0.358951

### Filling In Missing Data

- *fillna*: Fill NA/NaN values using the specified method

In [162]:
df

          0         1         2
0 -0.897483       NaN       NaN
1  0.681627       NaN       NaN
2  1.839922       NaN -0.580796
3  0.236613       NaN  0.377967
4 -0.950262  1.518228  0.299702
5 -1.091846 -1.637380 -0.366524
6  0.310111  0.333319 -0.358951

In [163]:
df.fillna(42)

          0          1          2
0 -0.897483  42.000000  42.000000
1  0.681627  42.000000  42.000000
2  1.839922  42.000000  -0.580796
3  0.236613  42.000000   0.377967
4 -0.950262   1.518228   0.299702
5 -1.091846  -1.637380  -0.366524
6  0.310111   0.333319  -0.358951

In [164]:
df

          0         1         2
0 -0.897483       NaN       NaN
1  0.681627       NaN       NaN
2  1.839922       NaN -0.580796
3  0.236613       NaN  0.377967
4 -0.950262  1.518228  0.299702
5 -1.091846 -1.637380 -0.366524
6  0.310111  0.333319 -0.358951

In [165]:
#if the value to fill in depends on the column
df.fillna({1: 0.5, 2: 0})

          0         1         2
0 -0.897483  0.500000  0.000000
1  0.681627  0.500000  0.000000
2  1.839922  0.500000 -0.580796
3  0.236613  0.500000  0.377967
4 -0.950262  1.518228  0.299702
5 -1.091846 -1.637380 -0.366524
6  0.310111  0.333319 -0.358951

In [166]:
df

          0         1         2
0 -0.897483       NaN       NaN
1  0.681627       NaN       NaN
2  1.839922       NaN -0.580796
3  0.236613       NaN  0.377967
4 -0.950262  1.518228  0.299702
5 -1.091846 -1.637380 -0.366524
6  0.310111  0.333319 -0.358951

In [167]:
df.fillna(0, inplace=True)

In [168]:
df

          0         1         2
0 -0.897483  0.000000  0.000000
1  0.681627  0.000000  0.000000
2  1.839922  0.000000 -0.580796
3  0.236613  0.000000  0.377967
4 -0.950262  1.518228  0.299702
5 -1.091846 -1.637380 -0.366524
6  0.310111  0.333319 -0.358951

- computing a value

In [169]:
df = pd.DataFrame(np.random.randn(6, 3))
df.iloc[2:, 1] = np.nan
df.iloc[4:, 2] = np.nan
df

          0         1         2
0  1.730617  0.694129  0.321434
1  1.357108 -0.822440 -1.005210
2  0.239465       NaN -0.284894
3  1.741487       NaN -1.239392
4 -0.640212       NaN       NaN
5 -1.695637       NaN       NaN

In [170]:
df.fillna(method='ffill')

/var/folders/ph/t7gwl3k17_l0cxktc3ll17600000gn/T/ipykernel_37272/253117906.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')

          0         1         2
0  1.730617  0.694129  0.321434
1  1.357108 -0.822440 -1.005210
2  0.239465 -0.822440 -0.284894
3  1.741487 -0.822440 -1.239392
4 -0.640212 -0.822440 -1.239392
5 -1.695637 -0.822440 -1.239392

In [171]:
df.ffill()

          0         1         2
0  1.730617  0.694129  0.321434
1  1.357108 -0.822440 -1.005210
2  0.239465 -0.822440 -0.284894
3  1.741487 -0.822440 -1.239392
4 -0.640212 -0.822440 -1.239392
5 -1.695637 -0.822440 -1.239392

In [172]:
#limit for forward and backward filling, maximum number of consecutive periods to fill
df.fillna(method='ffill', limit=2)

/var/folders/ph/t7gwl3k17_l0cxktc3ll17600000gn/T/ipykernel_37272/2930444409.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', limit=2)

          0         1         2
0  1.730617  0.694129  0.321434
1  1.357108 -0.822440 -1.005210
2  0.239465 -0.822440 -0.284894
3  1.741487 -0.822440 -1.239392
4 -0.640212       NaN -1.239392
5 -1.695637       NaN -1.239392

In [173]:
#we can use other functions
df.fillna(df.mean())

          0         1         2
0  1.730617  0.694129  0.321434
1  1.357108 -0.822440 -1.005210
2  0.239465 -0.064156 -0.284894
3  1.741487 -0.064156 -1.239392
4 -0.640212 -0.064156 -0.552016
5 -1.695637 -0.064156 -0.552016

In each column the substitution is done with that feature's mean.

In [174]:
df.mean()

0    0.455471
1   -0.064156
2   -0.552016
dtype: float64

Value on index 0 is the mean of column 0, value on index 1 is the mean of column 1, ... .

## Data Transformation

### Removing Duplicates

- *duplicated*
- drop_duplicated

In [175]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3 + ['two'],
                     'k2': [1, 1, 2, 3, 3, 4, 4]})
data

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [176]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [177]:
# data['k1'].duplicated() is equivalent to
data.duplicated(['k1'])

0    False
1    False
2     True
3     True
4     True
5     True
6     True
dtype: bool

In [178]:
data.drop_duplicates()

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [179]:
data['v1'] = range(7)
data

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [180]:
data.drop_duplicates(['k1', 'k2'], keep='last')

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

### Transforming Data Using a Function or Mapping

- map: Map values of Series according to input correspondence.

In [181]:
data = pd.DataFrame({
    'device': ['iPhone', 'Galaxy S21', 'MacBook Pro', 'Pixel 6',
               'ThinkPad', 'iPad', 'Surface Pro', 'galaxy tab', 'Macbook air'],
    'price': [999, 799, 1299, 599, 1099, 799, 999, 649, 999]
})

1. passing dictionary

In [182]:
device_to_brand = {
    'iphone': 'Apple',
    'macbook pro': 'Apple',
    'macbook air': 'Apple',
    'ipad': 'Apple',
    'galaxy s21': 'Samsung',
    'galaxy tab': 'Samsung',
    'pixel 6': 'Google',
    'thinkpad': 'Lenovo',
    'surface pro': 'Microsoft'
}

In [183]:
data['brand'] = data['device'].str.lower().map(device_to_brand)
data

        device  price      brand
0       iPhone    999      Apple
1   Galaxy S21    799    Samsung
2  MacBook Pro   1299      Apple
3      Pixel 6    599     Google
4     ThinkPad   1099     Lenovo
5         iPad    799      Apple
6  Surface Pro    999  Microsoft
7   galaxy tab    649    Samsung
8  Macbook air    999      Apple

### Replacing Values

- *replace*: Replace values given in *to_replace* with value.

In [184]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [185]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [186]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [187]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [188]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

### Discretization and Binning

- *cut*: Bin values into discrete intervals. Use cut when you need to segment and sort data values into bins

In [189]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 59, 45, 41, 32]

In [190]:
bins = [18, 25, 35, 60, 100]

In [191]:
values = pd.cut(ages, bins)

In [192]:
values

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (35, 60], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [193]:
type(values)

pandas.core.arrays.categorical.Categorical

In [194]:
values.codes # indexes of the bins

array([0, 0, 0, 1, 0, 0, 2, 1, 2, 2, 2, 1], dtype=int8)

In [213]:
values.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [214]:
values

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (35, 60], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [215]:
#These are the bin counts for the result of pandas.cut.
pd.value_counts(values)

/var/folders/ph/t7gwl3k17_l0cxktc3ll17600000gn/T/ipykernel_37272/404124905.py:2: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(values)

(18, 25]     5
(35, 60]     4
(25, 35]     3
(60, 100]    0
Name: count, dtype: int64

In [219]:
pd.Series(values).value_counts()

(18, 25]     5
(35, 60]     4
(25, 35]     3
(60, 100]    0
Name: count, dtype: int64

In [220]:
#parenthesis means that the side is open,
#while the square bracket means it is closed (inclusive).
#You can change which side is closed by passing right=False:
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [36, 61), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64, left]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [221]:
#You can also pass your own bin names by passing a list or array to the labels option:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']
new_ages = pd.cut(ages, bins, labels=group_names)

In [222]:
new_ages.categories

Index(['Youth', 'YoungAdult', 'MiddleAged', 'Senior'], dtype='object')

In [201]:
pd.value_counts(new_ages)

/var/folders/ph/t7gwl3k17_l0cxktc3ll17600000gn/T/ipykernel_37272/2120194990.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(new_ages)

Youth         5
MiddleAged    4
YoungAdult    3
Senior        0
Name: count, dtype: int64

In [202]:
# passing an integer, it will compute
#equal-length bins based on the minimum and maximum values in the data.
data = np.random.rand(20)
data

array([0.61188558, 0.80053869, 0.83633031, 0.26737153, 0.84619839,
       0.42410122, 0.84435377, 0.61065859, 0.69196305, 0.02982395,
       0.72735026, 0.87226225, 0.71473394, 0.16622515, 0.25804017,
       0.41619929, 0.94664104, 0.43469492, 0.92199036, 0.24123349])

In [203]:
pd.cut(data, 13).codes # takes minimum and maximum values, divides that interval in equal sized bins

array([ 8, 10, 11,  3, 11,  5, 11,  8,  9,  0,  9, 11,  9,  1,  3,  5, 12,
        5, 12,  2], dtype=int8)

In [223]:
pd.cut(data, 13).categories

IntervalIndex([ (0.0289, 0.1],   (0.1, 0.171], (0.171, 0.241], (0.241, 0.312],
               (0.312, 0.382], (0.382, 0.453], (0.453, 0.523], (0.523, 0.594],
               (0.594, 0.665], (0.665, 0.735], (0.735, 0.806], (0.806, 0.876],
               (0.876, 0.947]],
              dtype='interval[float64, right]')

### Computing Indicator/Dummy Variables/ One Hot Encoding (OHE)
- This converts a categorical variable into a “dummy” or “indicator” matrix.

- If a column in a DataFrame has k distinct values,
    - you would derive a matrix or DataFrame with k columns containing all 1s and 0s.
- pandas has a get_dummies function for doing this

In [204]:
df = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'b'],
                   'data1': range(6)})

In [205]:
df

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [229]:
pd.get_dummies(df['key']) # dtype='bool' is default

       a      b      c
0  False   True  False
1  False   True  False
2   True  False  False
3  False  False   True
4   True  False  False
5  False   True  False

In [207]:
pd.get_dummies(df['key'], dtype='int')

   a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [208]:
dummies = pd.get_dummies(df['key'], prefix='key')

In [209]:
dummies

   key_a  key_b  key_c
0  False   True  False
1  False   True  False
2   True  False  False
3  False  False   True
4   True  False  False
5  False   True  False

In [210]:
df[['data1']]

   data1
0      0
1      1
2      2
3      3
4      4
5      5

In [211]:
#to join the result in the original dataframe
df_with_dummy = df[['data1']].join(dummies)
df_with_dummy

   data1  key_a  key_b  key_c
0      0  False   True  False
1      1  False   True  False
2      2   True  False  False
3      3  False  False   True
4      4   True  False  False
5      5  False   True  False