In [1]:
import numpy as np
import pandas as pd

# Data Wrangling: Clean, Transform, Merge, Reshape

- Much of the programming work in data analysis and modeling is spent on data preparation
    - loading, cleaning, transforming, and rearranging.
    -  the way that data is stored in files or databases is not the way you need it.
- Fortunately, pandas along with the Python standard library provide you with a high-level, flexible, and high-performance set of core manipulations and algorithms to enable you to wrangle data into the right form without much trouble.

## Hierarchical Indexing

- Hierarchical indexing  enables you to have multiple (two or more) index levels on an axis.

In [2]:
data = pd.Series(np.random.randn(9),
                 index=[['a', 'a', 'a', 'b', 'b', 'c', 'c', 'd', 'd'],
                        [1, 2, 3, 1, 3, 1, 2, 2, 3]])
data

a  1    0.509519
   2   -0.241689
   3    0.755204
b  1    0.315528
   3   -0.089838
c  1   -0.625912
   2    1.080466
d  2    0.105905
   3    0.398256
dtype: float64

In [3]:
data.index

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 2),
            ('d', 3)],
           )

- partial indexing

In [4]:
data["a"]

1    0.509519
2   -0.241689
3    0.755204
dtype: float64

In [5]:
data["b"]

1    0.315528
3   -0.089838
dtype: float64

In [6]:
data["b":"d"]

b  1    0.315528
   3   -0.089838
c  1   -0.625912
   2    1.080466
d  2    0.105905
   3    0.398256
dtype: float64

In [7]:
data[["b","d"]]

b  1    0.315528
   3   -0.089838
d  2    0.105905
   3    0.398256
dtype: float64

In [8]:
data

a  1    0.509519
   2   -0.241689
   3    0.755204
b  1    0.315528
   3   -0.089838
c  1   -0.625912
   2    1.080466
d  2    0.105905
   3    0.398256
dtype: float64

In [9]:
data[:,3]

a    0.755204
b   -0.089838
d    0.398256
dtype: float64

<img src="https://drive.google.com/uc?id=1e5Qd4sSQvwu-4lKQHpn8IEeDR4CVs_Ns" width="60%" allow="autoplay"></img>

In [10]:
data

a  1    0.509519
   2   -0.241689
   3    0.755204
b  1    0.315528
   3   -0.089838
c  1   -0.625912
   2    1.080466
d  2    0.105905
   3    0.398256
dtype: float64

In [11]:
data.unstack()

          1         2         3
a  0.509519 -0.241689  0.755204
b  0.315528       NaN -0.089838
c -0.625912  1.080466       NaN
d       NaN  0.105905  0.398256

In [12]:
dataDF = data.unstack()
type(dataDF)

pandas.core.frame.DataFrame

In [13]:
dataDF.stack()

a  1    0.509519
   2   -0.241689
   3    0.755204
b  1    0.315528
   3   -0.089838
c  1   -0.625912
   2    1.080466
d  2    0.105905
   3    0.398256
dtype: float64

- In DataFrame, either axis can have a hierarchical index

In [14]:
frame = pd.DataFrame(np.arange(12).reshape((4, 3)),
                     index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
                     columns=[['Ohio', 'Ohio', 'Colorado'],
                              ['Green', 'Red', 'Green']])
frame

     Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

In [15]:
frame.index

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [16]:
frame.columns

MultiIndex([(    'Ohio', 'Green'),
            (    'Ohio',   'Red'),
            ('Colorado', 'Green')],
           )

In [17]:
frame["Ohio"]

     Green  Red
a 1      0    1
  2      3    4
b 1      6    7
  2      9   10

In [18]:
frame.loc["a",:]

   Ohio     Colorado
  Green Red    Green
1     0   1        2
2     3   4        5

In [19]:
frame.index.names = ['key1', 'key2']
frame.columns.names = ['state', 'color']
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

In [20]:
frame.sum(axis=1)

key1  key2
a     1        3
      2       12
b     1       21
      2       30
dtype: int64

## Database-style DataFrame Merges

- pandas.merge connects rows in DataFrames based on one or more keys.
- pandas.concat glues or stacks together objects along an axis.
- combine_first instance method enables splicing together overlapping data to fill in missing values in one object with values from another.

- Merge or join operations combine datasets by linking rows using one or more keys.
    - These operations are central to relational databases (e.g., SQL-based).

In [21]:
df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                    'data1': range(7)})
df2 = pd.DataFrame({'key': ['a', 'b', 'd'],
                    'data2': range(3)})

In [22]:
df1

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [23]:
df2

  key  data2
0   a      0
1   b      1
2   d      2

In [24]:
pd.merge(df1, df2) # natural join

  key  data1  data2
0   b      0      1
1   b      1      1
2   a      2      0
3   a      4      0
4   a      5      0
5   b      6      1

In [25]:
df1.merge(df2)

  key  data1  data2
0   b      0      1
1   b      1      1
2   a      2      0
3   a      4      0
4   a      5      0
5   b      6      1

In [26]:
pd.merge(df1, df2, on='key') # join using the attribute specified in the "on" parameter

  key  data1  data2
0   b      0      1
1   b      1      1
2   a      2      0
3   a      4      0
4   a      5      0
5   b      6      1

In [27]:
df3 = pd.DataFrame({'lkey': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                    'data1': range(7)})
df4 = pd.DataFrame({'rkey': ['a', 'b', 'd'],
                    'data2': range(3)})

In [28]:
df3

  lkey  data1
0    b      0
1    b      1
2    a      2
3    c      3
4    a      4
5    a      5
6    b      6

In [29]:
df4

  rkey  data2
0    a      0
1    b      1
2    d      2

In [30]:
#pd.merge(df3,df4) # dà errore perché non c'è una colonna comune (con lo stesso nome) su cui fare il merge. Devo specificarle, e lo faccio con la seguente istruzione.
pd.merge(df3,df4, left_on='lkey', right_on='rkey')

  lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    a      2    a      0
3    a      4    a      0
4    a      5    a      0
5    b      6    b      1

In [31]:
#we can specify the join attributes on the left and right tables
pd.merge(df3, df4, left_on='lkey', right_on='rkey')

  lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    a      2    a      0
3    a      4    a      0
4    a      5    a      0
5    b      6    b      1

In [32]:
pd.merge(df3, df4, left_on='lkey', right_on='rkey', how='left') # left join

  lkey  data1 rkey  data2
0    b      0    b    1.0
1    b      1    b    1.0
2    a      2    a    0.0
3    c      3  NaN    NaN
4    a      4    a    0.0
5    a      5    a    0.0
6    b      6    b    1.0

In [33]:
pd.merge(df3, df4, left_on='lkey', right_on='rkey', how='right') # right join

  lkey  data1 rkey  data2
0    a    2.0    a      0
1    a    4.0    a      0
2    a    5.0    a      0
3    b    0.0    b      1
4    b    1.0    b      1
5    b    6.0    b      1
6  NaN    NaN    d      2

In [34]:
pd.merge(df3, df4, left_on='lkey', right_on='rkey', how='outer') # outer join

  lkey  data1 rkey  data2
0    a    2.0    a    0.0
1    a    4.0    a    0.0
2    a    5.0    a    0.0
3    b    0.0    b    1.0
4    b    1.0    b    1.0
5    b    6.0    b    1.0
6    c    3.0  NaN    NaN
7  NaN    NaN    d    2.0

In [35]:
left = pd.DataFrame({'key1': ['foo', 'foo', 'bar'],
                     'key2': ['one', 'two', 'one'],
                     'lval': [1, 2, 3]})
right = pd.DataFrame({'key1': ['foo', 'foo', 'bar', 'bar'],
                      'key2': ['one', 'one', 'one', 'two'],
                      'rval': [4, 5, 6, 7]})

In [36]:
left

  key1 key2  lval
0  foo  one     1
1  foo  two     2
2  bar  one     3

In [37]:
right

  key1 key2  rval
0  foo  one     4
1  foo  one     5
2  bar  one     6
3  bar  two     7

In [38]:
pd.merge(left, right, on=['key1', 'key2'], how='outer')

  key1 key2  lval  rval
0  bar  one   3.0   6.0
1  bar  two   NaN   7.0
2  foo  one   1.0   4.0
3  foo  one   1.0   5.0
4  foo  two   2.0   NaN

This is the result of the merge, but dataframes left and right are still unchanged.

Treatment of overlapping column names:
-  merge has a suffixes option for specifying strings to append to overlapping names in the left and right DataFrame objects

In [39]:
pd.merge(left, right, on='key1')

  key1 key2_x  lval key2_y  rval
0  foo    one     1    one     4
1  foo    one     1    one     5
2  foo    two     2    one     4
3  foo    two     2    one     5
4  bar    one     3    one     6
5  bar    one     3    two     7

In [40]:
pd.merge(left, right, on='key1', suffixes=('_left', '_right'))

  key1 key2_left  lval key2_right  rval
0  foo       one     1        one     4
1  foo       one     1        one     5
2  foo       two     2        one     4
3  foo       two     2        one     5
4  bar       one     3        one     6
5  bar       one     3        two     7

- Merging on Index
    - the merge key(s) in a DataFrame can be found in its index.

In [41]:
left1 = pd.DataFrame({'key': ['a', 'b', 'a', 'a', 'b', 'c'],
                      'value': range(6)})
right1 = pd.DataFrame({'group_val': [3.5, 7]}, index=['a', 'b'])

In [42]:
left1

  key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [43]:
right1

   group_val
a        3.5
b        7.0

In [44]:
pd.merge(left1, right1, left_on='key', right_index=True)

  key  value  group_val
0   a      0        3.5
1   b      1        7.0
2   a      2        3.5
3   a      3        3.5
4   b      4        7.0

With this merge I've joined (default is inner join) the column key from left1 with the indexes (which can be considered a column of sorts) from right1.

In [45]:
pd.merge(left1, right1, left_on='key', right_index=True, how='outer')

  key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0
5   c      5        NaN

The same, but with outer join.

In [46]:
pd.merge(right1, right1, left_index=True, right_index=True)

   group_val_x  group_val_y
a          3.5          3.5
b          7.0          7.0

In [47]:
#we can use the indexes on both tables

left2 = pd.DataFrame([[1., 2.], [3., 4.], [5., 6.]],
                     index=['a', 'c', 'e'],
                     columns=['Ohio', 'Nevada'])
right2 = pd.DataFrame([[7., 8.], [9., 10.], [11., 12.], [13, 14]],
                      index=['b', 'c', 'd', 'e'],
                      columns=['Missouri', 'Alabama'])

In [48]:
left2

   Ohio  Nevada
a   1.0     2.0
c   3.0     4.0
e   5.0     6.0

In [49]:
right2

   Missouri  Alabama
b       7.0      8.0
c       9.0     10.0
d      11.0     12.0
e      13.0     14.0

In [50]:
pd.merge(left2, right2, left_index=True, right_index=True)

   Ohio  Nevada  Missouri  Alabama
c   3.0     4.0       9.0     10.0
e   5.0     6.0      13.0     14.0

- DataFrame has a convenient **join** instance for merging by index
 - It performs a left join on the join keys, preserving exactly the left frame’s row index

In [51]:
left2.join(right2)

   Ohio  Nevada  Missouri  Alabama
a   1.0     2.0       NaN      NaN
c   3.0     4.0       9.0     10.0
e   5.0     6.0      13.0     14.0

In [52]:
pd.merge(left2, right2, left_index=True, right_index=True, how='left')

   Ohio  Nevada  Missouri  Alabama
a   1.0     2.0       NaN      NaN
c   3.0     4.0       9.0     10.0
e   5.0     6.0      13.0     14.0

In [53]:
right2.join(left2)

   Missouri  Alabama  Ohio  Nevada
b       7.0      8.0   NaN     NaN
c       9.0     10.0   3.0     4.0
d      11.0     12.0   NaN     NaN
e      13.0     14.0   5.0     6.0

In [54]:
left2.join(right2, how='inner')

   Ohio  Nevada  Missouri  Alabama
c   3.0     4.0       9.0     10.0
e   5.0     6.0      13.0     14.0

In [55]:
left1

  key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [56]:
right1

   group_val
a        3.5
b        7.0

In [57]:
# we can join by index and attribute as with the merge
left1.join(right1, on='key')

  key  value  group_val
0   a      0        3.5
1   b      1        7.0
2   a      2        3.5
3   a      3        3.5
4   b      4        7.0
5   c      5        NaN

Keep in mind that the default is a left join, so the key column is preserved exactly as it is.

In [58]:
#joining more tables
another = pd.DataFrame([[7., 8.], [9., 10.], [11., 12.], [16., 17.]],
                       index=['a', 'c', 'e', 'f'],
                       columns=['New York', 'Oregon'])
another

   New York  Oregon
a       7.0     8.0
c       9.0    10.0
e      11.0    12.0
f      16.0    17.0

In [59]:
left2.join([right2, another])

   Ohio  Nevada  Missouri  Alabama  New York  Oregon
a   1.0     2.0       NaN      NaN       7.0     8.0
c   3.0     4.0       9.0     10.0       9.0    10.0
e   5.0     6.0      13.0     14.0      11.0    12.0

## Concatenating Along an Axis

- Another kind of data combination operation is referred to interchangeably as concatenation, binding, or stacking

In [60]:
arr = np.arange(12).reshape((3, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [61]:
np.concatenate([arr, arr])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [62]:
np.concatenate([arr, arr], axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In the context of pandas objects such as Series and DataFrame, having labeled axes
enable you to further generalize array concatenation

In [63]:
s1 = pd.Series([0, 1], index=['a', 'b'])
s2 = pd.Series([2, 3, 4], index=['c', 'd', 'e'])
s3 = pd.Series([5, 6], index=['f', 'g'])

In [64]:
s1

a    0
b    1
dtype: int64

In [65]:
s2

c    2
d    3
e    4
dtype: int64

In [66]:
s3

f    5
g    6
dtype: int64

In [67]:
pd.concat([s1,s2,s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: int64

In [68]:
pd.concat([s1,s2,s3], axis=1)

     0    1    2
a  0.0  NaN  NaN
b  1.0  NaN  NaN
c  NaN  2.0  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [69]:
s4 = pd.concat([s1, s3])

In [70]:
s4

a    0
b    1
f    5
g    6
dtype: int64

In [71]:
pd.concat([s1, s4], axis=1)

     0  1
a  0.0  0
b  1.0  1
f  NaN  5
g  NaN  6

In [72]:
s1

a    0
b    1
dtype: int64

In [73]:
s4

a    0
b    1
f    5
g    6
dtype: int64

In [74]:
pd.concat([s1, s4], axis=1, join ='inner')

   0  1
a  0  0
b  1  1

- A potential issue is that the concatenated pieces are not identifiable in the result.

In [75]:
pd.concat([s1,s2,s3], keys=['s1','s2','s3'])

s1  a    0
    b    1
s2  c    2
    d    3
    e    4
s3  f    5
    g    6
dtype: int64

In [76]:
pd.concat([s1,s2,s3], keys=['s1','s2','s3']).unstack()

      a    b    c    d    e    f    g
s1  0.0  1.0  NaN  NaN  NaN  NaN  NaN
s2  NaN  NaN  2.0  3.0  4.0  NaN  NaN
s3  NaN  NaN  NaN  NaN  NaN  5.0  6.0

- The same logic extends to DataFrame objects:

In [77]:
df1 = pd.DataFrame(np.arange(6).reshape(3, 2), index=['a', 'b', 'c'],
                   columns=['one', 'two'])
df2 = pd.DataFrame(5 + np.arange(4).reshape(2, 2), index=['a', 'c'],
                   columns=['three', 'four'])

In [78]:
df1

   one  two
a    0    1
b    2    3
c    4    5

In [79]:
df2

   three  four
a      5     6
c      7     8

In [80]:
pd.concat([df1,df2])

   one  two  three  four
a  0.0  1.0    NaN   NaN
b  2.0  3.0    NaN   NaN
c  4.0  5.0    NaN   NaN
a  NaN  NaN    5.0   6.0
c  NaN  NaN    7.0   8.0

In [81]:
pd.concat([df1,df2], axis=1)

   one  two  three  four
a    0    1    5.0   6.0
b    2    3    NaN   NaN
c    4    5    7.0   8.0

In [82]:
pd.concat([df1,df2], axis=1, keys =['df1','df2'])

  df1       df2
  one two three four
a   0   1   5.0  6.0
b   2   3   NaN  NaN
c   4   5   7.0  8.0

- when the row index does not contain any relevant data

In [83]:
df1 = pd.DataFrame(np.random.randn(3, 4), columns=['a', 'b', 'c', 'd'])
df2 = pd.DataFrame(np.random.randn(2, 3), columns=['b', 'd', 'a'])

In [84]:
df1

          a         b         c         d
0 -0.383091 -0.954700 -0.297448  1.380842
1 -1.558154  0.537199  0.402553  1.551205
2 -1.289085  0.778289 -0.486159 -0.722079

In [85]:
df2

          b         d         a
0  0.392953 -0.317669 -0.658292
1  1.644490 -0.595871  0.152074

In [86]:
pd.concat([df1,df2])

          a         b         c         d
0 -0.383091 -0.954700 -0.297448  1.380842
1 -1.558154  0.537199  0.402553  1.551205
2 -1.289085  0.778289 -0.486159 -0.722079
0 -0.658292  0.392953       NaN -0.317669
1  0.152074  1.644490       NaN -0.595871

In [87]:
pd.concat([df1,df2], ignore_index=True)

          a         b         c         d
0 -0.383091 -0.954700 -0.297448  1.380842
1 -1.558154  0.537199  0.402553  1.551205
2 -1.289085  0.778289 -0.486159 -0.722079
3 -0.658292  0.392953       NaN -0.317669
4  0.152074  1.644490       NaN -0.595871

In [88]:
pd.concat([df1,df2], axis=1)

          a         b         c         d         b         d         a
0 -0.383091 -0.954700 -0.297448  1.380842  0.392953 -0.317669 -0.658292
1 -1.558154  0.537199  0.402553  1.551205  1.644490 -0.595871  0.152074
2 -1.289085  0.778289 -0.486159 -0.722079       NaN       NaN       NaN

# Data Aggregation and Group Operations

- Categorizing a dataset and applying a function to each group is often a critical component of a data analysis workflow.
- After loading, merging, and preparing a dataset, you may need to compute group statistics or pivot tables for reporting or visualization purposes.

### GroupBy Mechanics
- data contained in a pandas object is split into groups based on one or more keys.
    - The splitting is performed on a particular axis of an object.
        - For example, a DataFrame can be grouped on its rows (axis=0) or its columns (axis=1).
- a function is applied to each group, producing a new value.
- the results of all those function applications are combined into a result object.

<img src="https://drive.google.com/uc?id=1B559BfpzVoV6i9QdzmeA-GLrGdZTd-2s" width=500>

In [89]:
import pandas as pd
import numpy as np

In [90]:
df = pd.DataFrame({'key1' : ['a', 'a', 'b', 'b', 'a'],
                   'key2' : ['one', 'two', 'one', 'two', 'one'],
                   'data1' : np.random.randn(5),
                   'data2' : np.random.randn(5)})
df

  key1 key2     data1     data2
0    a  one -0.355540  1.241239
1    a  two  0.308157  0.787182
2    b  one  0.580458 -1.548038
3    b  two  0.198083 -0.999880
4    a  one -0.157219 -0.984870

- We want to compute the mean of the data1 column using the labels from key1.

In [91]:
grouped = df['data1'].groupby(df['key1'])

In [92]:
grouped

- This grouped variable is now a GroupBy object.
- It has not actually computed anything yet except for some intermediate data about the group key df['key1'].
- The idea is that this object has all of the information needed to then apply some operation to each of the groups.

In [93]:
grouped.max()

key1
a    0.308157
b    0.580458
Name: data1, dtype: float64

In [94]:
grouped.mean()

key1
a   -0.068200
b    0.389271
Name: data1, dtype: float64

In [95]:
grouped.sum()

key1
a   -0.204601
b    0.778541
Name: data1, dtype: float64

In [96]:
df['data1'].groupby([df['key1'], df['key2']]).mean()

key1  key2
a     one    -0.256379
      two     0.308157
b     one     0.580458
      two     0.198083
Name: data1, dtype: float64

In [97]:
df['data1'].groupby([df['key1'], df['key2']]).mean().unstack()

key2       one       two
key1
a    -0.256379  0.308157
b     0.580458  0.198083

In [98]:
df

  key1 key2     data1     data2
0    a  one -0.355540  1.241239
1    a  two  0.308157  0.787182
2    b  one  0.580458 -1.548038
3    b  two  0.198083 -0.999880
4    a  one -0.157219 -0.984870

In [99]:
#df.groupby(df['key1']).mean() # la media vuole in input dei numeri, ma non tutti i valori sono numerici in questo caso. Quindi uso numeric_only=true

In [100]:
df.groupby(df['key1']).mean(numeric_only=True)

         data1     data2
key1
a    -0.068200  0.347850
b     0.389271 -1.273959

- Note that there is no key2 column in the result.
    - df['key2'] is not numeric data

    
    
- the method size returns a Series containing group sizes

In [101]:
df.groupby(['key1', 'key2']).size()

key1  key2
a     one     2
      two     1
b     one     1
      two     1
dtype: int64

- Iterating Over Groups
    - The GroupBy object supports iteration,
    - It generates a sequence of 2-tuples containing the group name along with the chunk of data

In [102]:
for name, group in df.groupby('key1'):
    print(name)
    print(group)
    print("\n\n")

a
  key1 key2     data1     data2
0    a  one -0.355540  1.241239
1    a  two  0.308157  0.787182
4    a  one -0.157219 -0.984870



b
  key1 key2     data1     data2
2    b  one  0.580458 -1.548038
3    b  two  0.198083 -0.999880

In [103]:
# multiple keys in the group by clause
for (k1, k2), group in df.groupby(['key1', 'key2']):
    print((k1, k2))
    print(group)
    print("\n\n")

('a', 'one')
  key1 key2     data1     data2
0    a  one -0.355540  1.241239
4    a  one -0.157219 -0.984870



('a', 'two')
  key1 key2     data1     data2
1    a  two  0.308157  0.787182



('b', 'one')
  key1 key2     data1     data2
2    b  one  0.580458 -1.548038



('b', 'two')
  key1 key2     data1    data2
3    b  two  0.198083 -0.99988

- By default groupby groups on axis=0, but you can group on any of the other axes.

In [104]:
df.dtypes

key1      object
key2      object
data1    float64
data2    float64
dtype: object

In [105]:
df

  key1 key2     data1     data2
0    a  one -0.355540  1.241239
1    a  two  0.308157  0.787182
2    b  one  0.580458 -1.548038
3    b  two  0.198083 -0.999880
4    a  one -0.157219 -0.984870

In [106]:
grouped = df.groupby(df.dtypes, axis=1)

/var/folders/ph/t7gwl3k17_l0cxktc3ll17600000gn/T/ipykernel_29480/521057107.py:1: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  grouped = df.groupby(df.dtypes, axis=1)

In [107]:
grouped

In [108]:
for dtype, group in grouped:
    print(dtype)
    print(group)

float64
      data1     data2
0 -0.355540  1.241239
1  0.308157  0.787182
2  0.580458 -1.548038
3  0.198083 -0.999880
4 -0.157219 -0.984870
object
  key1 key2
0    a  one
1    a  two
2    b  one
3    b  two
4    a  one

### Selecting a Column or Subset of Columns
- Indexing a GroupBy object created from a DataFrame with a column name or array of column names has the effect of column subsetting for aggregation

In [109]:
df.groupby('key1')['data1']
# it is equal to df['data1'].groupby(df['key1'])

In [110]:
df.groupby('key1')[['data2']]
# it is equal to df[['data2']].groupby(df['key1'])

In [111]:
df.groupby('key1')['data2'].mean()

key1
a    0.347850
b   -1.273959
Name: data2, dtype: float64

### Grouping with Dicts and Series

In [112]:
people = pd.DataFrame(np.random.randn(5, 5),
                      columns=['a', 'b', 'c', 'd', 'e'],
                      index=['Joe', 'Steve', 'Wes', 'Jim', 'Travis'])

In [113]:
people

               a         b         c         d         e
Joe     0.268905  0.263433  1.130164  0.882349  0.823208
Steve  -1.074809  1.269772 -0.784222 -0.013128 -0.738142
Wes     0.437717  0.067971  0.036544  0.190487 -0.682399
Jim     0.440536  0.835617  0.220794 -1.814189  0.909497
Travis -1.308770 -0.897716  0.565847  2.257300 -0.608378

In [114]:
mapping = {'a': 'red', 'b': 'red', 'c': 'blue',
           'd': 'blue', 'e': 'orange'}

In [115]:
by_column = people.groupby(mapping, axis=1)

/var/folders/ph/t7gwl3k17_l0cxktc3ll17600000gn/T/ipykernel_29480/3111365124.py:1: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  by_column = people.groupby(mapping, axis=1)

In [116]:
by_column.sum()

            blue    orange       red
Joe     2.012513  0.823208  0.532338
Steve  -0.797350 -0.738142  0.194963
Wes     0.227031 -0.682399  0.505688
Jim    -1.593395  0.909497  1.276153
Travis  2.823148 -0.608378 -2.206486

- The same functionality holds for Series, which can be viewed as a fixed-size mapping

In [117]:
map_series = pd.Series(mapping)

In [118]:
map_series

a       red
b       red
c      blue
d      blue
e    orange
dtype: object

In [119]:
by_columnSeries = people.groupby(map_series, axis=1)

/var/folders/ph/t7gwl3k17_l0cxktc3ll17600000gn/T/ipykernel_29480/3304494313.py:1: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  by_columnSeries = people.groupby(map_series, axis=1)

In [120]:
by_columnSeries.mean()

            blue    orange       red
Joe     1.006257  0.823208  0.266169
Steve  -0.398675 -0.738142  0.097481
Wes     0.113515 -0.682399  0.252844
Jim    -0.796697  0.909497  0.638077
Travis  1.411574 -0.608378 -1.103243

### Grouping with Functions
- Any function passed as a group key will be called once per index value, with the return values being used as the group names.

In [121]:
people

               a         b         c         d         e
Joe     0.268905  0.263433  1.130164  0.882349  0.823208
Steve  -1.074809  1.269772 -0.784222 -0.013128 -0.738142
Wes     0.437717  0.067971  0.036544  0.190487 -0.682399
Jim     0.440536  0.835617  0.220794 -1.814189  0.909497
Travis -1.308770 -0.897716  0.565847  2.257300 -0.608378

In [122]:
people.groupby(len).sum()

          a         b         c         d         e
3  1.147158  1.167021  1.387502 -0.741353  1.050306
5 -1.074809  1.269772 -0.784222 -0.013128 -0.738142
6 -1.308770 -0.897716  0.565847  2.257300 -0.608378

In [123]:
def name_with_j(x):
  if x.startswith("J"):
    return True
  return False

In [124]:
name_with_j("Jim")

True

In [125]:
name_with_j("Albert")

False

In [126]:
people.groupby(name_with_j).sum()

              a         b         c         d         e
False -1.945862  0.440027 -0.181831  2.434659 -2.028920
True   0.709441  1.099050  1.350958 -0.931840  1.732705

- Mixing functions with arrays, dicts, or Series is not a problem

In [127]:
people

               a         b         c         d         e
Joe     0.268905  0.263433  1.130164  0.882349  0.823208
Steve  -1.074809  1.269772 -0.784222 -0.013128 -0.738142
Wes     0.437717  0.067971  0.036544  0.190487 -0.682399
Jim     0.440536  0.835617  0.220794 -1.814189  0.909497
Travis -1.308770 -0.897716  0.565847  2.257300 -0.608378

In [128]:
key_list = ['one', 'one', 'one', 'two', 'two']
people.groupby([len, key_list]).min()

              a         b         c         d         e
3 one  0.268905  0.067971  0.036544  0.190487 -0.682399
  two  0.440536  0.835617  0.220794 -1.814189  0.909497
5 one -1.074809  1.269772 -0.784222 -0.013128 -0.738142
6 two -1.308770 -0.897716  0.565847  2.257300 -0.608378

### Data Aggregation

<img src="https://drive.google.com/uc?id=1Azj6fJq9KLaSZoA0GSLl2OwJCUzw-Ba2" width=500>

- Aggregations refer to any data transformation that produces scalar values from arrays.

- Many common aggregations, such as those found in the above table, have optimized implementations.

- You are not limited to only this set of methods.
    - For example quantile is not explicitly implemented for GroupBy, it is a Series method and thus available for use.

In [129]:
grouped = df.groupby('key1')
grouped['data1'].quantile()

key1
a   -0.157219
b    0.389271
Name: data1, dtype: float64

-  you can implement a custom function
- you have to pass the function to the agg() method

In [130]:
def peak_to_peak(arr):
    return arr.max() - arr.min()

In [131]:
grouped = df.groupby('key1')

In [132]:
grouped['data1'].agg(peak_to_peak)

key1
a    0.663697
b    0.382375
Name: data1, dtype: float64

In [133]:
#Note that the method describes works applied to groups
grouped.describe()

     data1                                                              \
     count      mean       std       min       25%       50%       75%
key1
a      3.0 -0.068200  0.340686 -0.355540 -0.256379 -0.157219  0.075469
b      2.0  0.389271  0.270380  0.198083  0.293677  0.389271  0.484864

               data2                                                    \
           max count      mean       std       min       25%       50%
key1
a     0.308157   3.0  0.347850  1.176286 -0.984870 -0.098844  0.787182
b     0.580458   2.0 -1.273959  0.387606 -1.548038 -1.410999 -1.273959


          75%       max
key1
a     1.01421  1.241239
b    -1.13692 -0.999880

## [BONUS] Column-Wise and Multiple Function Application

In [134]:
#caricare il file su colab
tips = pd.read_csv('data/tips.csv')

In [135]:
tips.head(10)

   total_bill   tip smoker  day    time  size
0       16.99  1.01     No  Sun  Dinner     2
1       10.34  1.66     No  Sun  Dinner     3
2       21.01  3.50     No  Sun  Dinner     3
3       23.68  3.31     No  Sun  Dinner     2
4       24.59  3.61     No  Sun  Dinner     4
5       25.29  4.71     No  Sun  Dinner     4
6        8.77  2.00     No  Sun  Dinner     2
7       26.88  3.12     No  Sun  Dinner     4
8       15.04  1.96     No  Sun  Dinner     2
9       14.78  3.23     No  Sun  Dinner     2

In [136]:
tips.shape

(244, 6)

In [137]:
tips['tip_pct'] = tips['tip'] / tips['total_bill']

In [138]:
tips.head(10)

   total_bill   tip smoker  day    time  size   tip_pct
0       16.99  1.01     No  Sun  Dinner     2  0.059447
1       10.34  1.66     No  Sun  Dinner     3  0.160542
2       21.01  3.50     No  Sun  Dinner     3  0.166587
3       23.68  3.31     No  Sun  Dinner     2  0.139780
4       24.59  3.61     No  Sun  Dinner     4  0.146808
5       25.29  4.71     No  Sun  Dinner     4  0.186240
6        8.77  2.00     No  Sun  Dinner     2  0.228050
7       26.88  3.12     No  Sun  Dinner     4  0.116071
8       15.04  1.96     No  Sun  Dinner     2  0.130319
9       14.78  3.23     No  Sun  Dinner     2  0.218539

- aggregating a Series or all of the columns of a DataFrame is a matter of using aggregate with the desired function or calling a method like mean or std.
- you may want to aggregate using a different function depending on the column, or multiple functions at once.

In [139]:
#this is a simple grouping
grouped = tips.groupby(['day', 'smoker'])

In [140]:
grouped_pct = grouped['tip_pct']

In [141]:
# for simple statistics, you can pass the name of the function as a string
grouped_pct.agg('mean')

day   smoker
Fri   No        0.151650
      Yes       0.174783
Sat   No        0.158048
      Yes       0.147906
Sun   No        0.160113
      Yes       0.187250
Thur  No        0.160298
      Yes       0.163863
Name: tip_pct, dtype: float64

In [142]:
grouped_pct.mean()

day   smoker
Fri   No        0.151650
      Yes       0.174783
Sat   No        0.158048
      Yes       0.147906
Sun   No        0.160113
      Yes       0.187250
Thur  No        0.160298
      Yes       0.163863
Name: tip_pct, dtype: float64

In [143]:
# If you pass a list of functions or function names, you get back a DataFrame with column names taken from the functions
grouped_pct.agg(['mean', 'std', peak_to_peak])

                 mean       std  peak_to_peak
day  smoker
Fri  No      0.151650  0.028123      0.067349
     Yes     0.174783  0.051293      0.159925
Sat  No      0.158048  0.039767      0.235193
     Yes     0.147906  0.061375      0.290095
Sun  No      0.160113  0.042347      0.193226
     Yes     0.187250  0.154134      0.644685
Thur No      0.160298  0.038774      0.193350
     Yes     0.163863  0.039389      0.151240

In [144]:
grouped_pct.agg([('Media', 'mean'), ('Deviazione std', np.std)])

/var/folders/ph/t7gwl3k17_l0cxktc3ll17600000gn/T/ipykernel_29480/2786537713.py:1: FutureWarning: The provided callable <function std at 0x1085a7ce0> is currently using SeriesGroupBy.std. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "std" instead.
  grouped_pct.agg([('Media', 'mean'), ('Deviazione std', np.std)])

                Media  Deviazione std
day  smoker
Fri  No      0.151650        0.028123
     Yes     0.174783        0.051293
Sat  No      0.158048        0.039767
     Yes     0.147906        0.061375
Sun  No      0.160113        0.042347
     Yes     0.187250        0.154134
Thur No      0.160298        0.038774
     Yes     0.163863        0.039389

In [145]:
#you can specify a list of functions to apply to all of the columns or different functions per column
#all columns
functions = ['count', 'mean', 'max']

In [146]:
grouped[['tip_pct', 'total_bill']].agg(functions)

            tip_pct                     total_bill
              count      mean       max      count       mean    max
day  smoker
Fri  No           4  0.151650  0.187735          4  18.420000  22.75
     Yes         15  0.174783  0.263480         15  16.813333  40.17
Sat  No          45  0.158048  0.291990         45  19.661778  48.33
     Yes         42  0.147906  0.325733         42  21.276667  50.81
Sun  No          57  0.160113  0.252672         57  20.506667  48.17
     Yes         19  0.187250  0.710345         19  24.120000  45.35
Thur No          45  0.160298  0.266312         45  17.113111  41.19
     Yes         17  0.163863  0.241255         17  19.190588  43.11

In [147]:
#aggregation on a selection of the columns

In [148]:
grouped.agg({'tip' : np.max, 'size' : 'sum'})

/var/folders/ph/t7gwl3k17_l0cxktc3ll17600000gn/T/ipykernel_29480/683326323.py:1: FutureWarning: The provided callable <function max at 0x1085a71a0> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  grouped.agg({'tip' : np.max, 'size' : 'sum'})

               tip  size
day  smoker
Fri  No       3.50     9
     Yes      4.73    31
Sat  No       9.00   115
     Yes     10.00   104
Sun  No       6.00   167
     Yes      6.50    49
Thur No       6.70   112
     Yes      5.00    40

## [BONUS] Apply: General split-apply-combine

- We want to select the top five values by group

In [149]:
def top(df, n=5, column='tip_pct'):
    return df.sort_values(by=column)[-n:]

In [150]:
top(tips, n=6)

     total_bill   tip smoker  day    time  size   tip_pct
109       14.31  4.00    Yes  Sat  Dinner     2  0.279525
183       23.17  6.50    Yes  Sun  Dinner     4  0.280535
232       11.61  3.39     No  Sat  Dinner     2  0.291990
67         3.07  1.00    Yes  Sat  Dinner     1  0.325733
178        9.60  4.00    Yes  Sun  Dinner     2  0.416667
172        7.25  5.15    Yes  Sun  Dinner     2  0.710345

In [151]:
tips[["day","total_bill"]].groupby(["day"]).max()

      total_bill
day
Fri        40.17
Sat        50.81
Sun        48.17
Thur       43.11

In [152]:
tips[["day","total_bill"]].groupby("day").apply(top, column="total_bill")

/var/folders/ph/t7gwl3k17_l0cxktc3ll17600000gn/T/ipykernel_29480/3809692214.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  tips[["day","total_bill"]].groupby("day").apply(top, column="total_bill")

           day  total_bill
day
Fri  91    Fri       22.49
     94    Fri       22.75
     96    Fri       27.28
     90    Fri       28.97
     95    Fri       40.17
Sat  23    Sat       39.42
     102   Sat       44.30
     59    Sat       48.27
     212   Sat       48.33
     170   Sat       50.81
Sun  11    Sun       35.26
     112   Sun       38.07
     184   Sun       40.55
     182   Sun       45.35
     156   Sun       48.17
Thur 83   Thur       32.68
     141  Thur       34.30
     85   Thur       34.83
     142  Thur       41.19
     197  Thur       43.11

In [153]:
tips[["day","total_bill"]].groupby("day").apply(top, n=1, column="total_bill")

/var/folders/ph/t7gwl3k17_l0cxktc3ll17600000gn/T/ipykernel_29480/223960879.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  tips[["day","total_bill"]].groupby("day").apply(top, n=1, column="total_bill")

           day  total_bill
day
Fri  95    Fri       40.17
Sat  170   Sat       50.81
Sun  156   Sun       48.17
Thur 197  Thur       43.11

## Pivot Tables

- A pivot table
    - aggregates a table of data by one or more keys,
    - arranges the data in a rectangle with some of the group keys along the rows and the columns.

In [154]:
#caricare il file su colab
tips = pd.read_csv('data/tips.csv')

In [155]:
tips.head(10)

   total_bill   tip smoker  day    time  size
0       16.99  1.01     No  Sun  Dinner     2
1       10.34  1.66     No  Sun  Dinner     3
2       21.01  3.50     No  Sun  Dinner     3
3       23.68  3.31     No  Sun  Dinner     2
4       24.59  3.61     No  Sun  Dinner     4
5       25.29  4.71     No  Sun  Dinner     4
6        8.77  2.00     No  Sun  Dinner     2
7       26.88  3.12     No  Sun  Dinner     4
8       15.04  1.96     No  Sun  Dinner     2
9       14.78  3.23     No  Sun  Dinner     2

In [156]:
#tips.pivot_table(index=['day', 'smoker']) # the default aggregation type is mean

In [157]:
tips.pivot_table(index=['day', 'smoker'], aggfunc='first')

             size    time   tip  total_bill
day  smoker
Fri  No         2  Dinner  3.50       22.49
     Yes        2  Dinner  3.00       28.97
Sat  No         3  Dinner  3.35       20.65
     Yes        4  Dinner  3.00       38.01
Sun  No         2  Dinner  1.01       16.99
     Yes        2  Dinner  3.00       17.51
Thur No         4   Lunch  4.00       27.20
     Yes        2   Lunch  3.00       19.44

In [158]:
tips.pivot_table(index=['day', 'smoker'], values=['size', 'tip'], aggfunc='sum')

             size     tip
day  smoker
Fri  No         9   11.25
     Yes       31   40.71
Sat  No       115  139.63
     Yes      104  120.77
Sun  No       167  180.57
     Yes       49   66.82
Thur No       112  120.32
     Yes       40   51.51

In [159]:
tips.pivot_table(index=['day', 'size'], values='tip', columns='smoker')

smoker           No       Yes
day  size
Fri  1          NaN  1.920000
     2     2.750000  2.620000
     3     3.000000       NaN
     4          NaN  4.730000
Sat  1     1.000000  1.000000
     2     2.563200  2.476786
     3     3.412500  4.568333
     4     4.800000  3.335000
     5          NaN  3.000000
Sun  2     2.582222  3.345000
     3     2.937273  3.625000
     4     3.962500  5.090000
     5     5.070000  2.000000
     6     5.000000       NaN
Thur 1     1.830000       NaN
     2     2.341714  2.713846
     3     1.770000  3.615000
     4     4.030000  4.500000
     5     5.000000       NaN
     6     5.300000       NaN

In [160]:
tips.pivot_table(index=['day', 'size'], values='tip', columns='smoker', margins=True) # margins=True aggiunge la colonna All

smoker           No       Yes       All
day  size
Fri  1          NaN  1.920000  1.920000
     2     2.750000  2.620000  2.644375
     3     3.000000       NaN  3.000000
     4          NaN  4.730000  4.730000
Sat  1     1.000000  1.000000  1.000000
     2     2.563200  2.476786  2.517547
     3     3.412500  4.568333  3.797778
     4     4.800000  3.335000  4.123846
     5          NaN  3.000000  3.000000
Sun  2     2.582222  3.345000  2.816923
     3     2.937273  3.625000  3.120667
     4     3.962500  5.090000  4.087778
     5     5.070000  2.000000  4.046667
     6     5.000000       NaN  5.000000
Thur 1     1.830000       NaN  1.830000
     2     2.341714  2.713846  2.442500
     3     1.770000  3.615000  2.692500
     4     4.030000  4.500000  4.218000
     5     5.000000       NaN  5.000000
     6     5.300000       NaN  5.300000
All        2.991854  3.008710  2.998279

In [161]:
tips.pivot_table(index=['day', 'size'], values='tip', columns='smoker', margins=True, fill_value=-1000)

smoker              No          Yes       All
day  size
Fri  1    -1000.000000     1.920000  1.920000
     2        2.750000     2.620000  2.644375
     3        3.000000 -1000.000000  3.000000
     4    -1000.000000     4.730000  4.730000
Sat  1        1.000000     1.000000  1.000000
     2        2.563200     2.476786  2.517547
     3        3.412500     4.568333  3.797778
     4        4.800000     3.335000  4.123846
     5    -1000.000000     3.000000  3.000000
Sun  2        2.582222     3.345000  2.816923
     3        2.937273     3.625000  3.120667
     4        3.962500     5.090000  4.087778
     5        5.070000     2.000000  4.046667
     6        5.000000 -1000.000000  5.000000
Thur 1        1.830000 -1000.000000  1.830000
     2        2.341714     2.713846  2.442500
     3        1.770000     3.615000  2.692500
     4        4.030000     4.500000  4.218000
     5        5.000000 -1000.000000  5.000000
     6        5.300000 -1000.000000  5.300000
All           2.991854     3.008710  2.998279

## [Bonus] Cross-Tabulations: Crosstab
- A cross-tabulation (or crosstab for short) is a special case of a pivot table that computes group frequencies.

In [162]:
states= ['USA','USA','UK','IT','UK','UK','IT','USA']
gender= ['M','F','F','M','M','M','F','M']

In [163]:
data = pd.DataFrame({'states':states,'gender':gender})

In [164]:
data

  states gender
0    USA      M
1    USA      F
2     UK      F
3     IT      M
4     UK      M
5     UK      M
6     IT      F
7    USA      M

In [165]:
pd.crosstab(data.states, data.gender)

gender  F  M
states
IT      1  1
UK      1  2
USA     1  2

In [166]:
pd.crosstab(data.gender, data.states)

states  IT  UK  USA
gender
F        1   1    1
M        1   2    2

In [167]:
pd.crosstab(data.gender, data.states, margins=True)

states  IT  UK  USA  All
gender
F        1   1    1    3
M        1   2    2    5
All      2   3    3    8